// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "Libs/predict_star_number_mod.dll";





        [DllImport(__DllName, EntryPoint = "get_predicted_values", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double get_predicted_values(double* record_pointer, System.UIntPtr recorde_length, byte* model_pointer, System.UIntPtr model_length);


    }



}
